### ISSUE TITLE
UPSTREAMS targets active : 405 Not Allowed 

### ISSUE THREAD

**Issue by Serikpa** [mybuilder/kongfig#121]
Hi,

I use kongfig in my environment with kong 0.12.1.  When I run the following command: 

> kongfig dump --host localhost:8001 > config.yml

I received the following error:

Error: http://localhost:8001/upstreams/74d6359b-ed58-4198-9e1b-a441341948c2/targets/active/: 405 Not Allowed 
 Error: http://localhost:8001/upstreams/74d6359b-ed58-4198-9e1b-a441341948c2/targets/active/: 405 Not Allowed
    at /usr/lib/node_modules/kongfig/lib/adminApi.js:133:25
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Could you tell me what can i do to solve my problem?

**Comment by Serikpa** [comment]
Duplicate issue
