### ISSUE TITLE
version 1.5.x broke something

### ISSUE THREAD

**Issue by hreidar** [mybuilder/kongfig#125]
Hi, I just updated kongfig via npm and it seems to have boke something:

~~~~
$ sudo npm install -g kongfig@1.5.1
/usr/local/bin/kongfig -> /usr/local/lib/node_modules/kongfig/bin/kongfig
/usr/local/lib
└─┬ kongfig@1.5.1 
  ├─┬ babel-polyfill@6.26.0 
  │ ├─┬ babel-runtime@6.26.0 
  │ │ └── regenerator-runtime@0.11.1 
  │ ├── core-js@2.5.3 
  │ └── regenerator-runtime@0.10.5 
  ├── colors@1.1.2 
  ├── commander@2.14.1 
  ├─┬ invariant@2.2.3 
  │ └─┬ loose-envify@1.3.1 
  │   └── js-tokens@3.0.2 
  ├─┬ isomorphic-fetch@2.2.1 
  │ ├─┬ node-fetch@1.7.3 
  │ │ ├─┬ encoding@0.1.12 
  │ │ │ └── iconv-lite@0.4.19 
  │ │ └── is-stream@1.1.0 
  │ └── whatwg-fetch@2.0.3 
  ├─┬ js-yaml@3.10.0 
  │ ├─┬ argparse@1.0.10 
  │ │ └── sprintf-js@1.0.3 
  │ └── esprima@4.0.0 
  ├── minimist@1.2.0 
  ├── object-assign@4.1.1 
  ├─┬ pad@2.0.3 
  │ └─┬ wcwidth@1.0.1 
  │   └─┬ defaults@1.0.3 
  │     └── clone@1.0.3 
  ├── prettyjson@1.2.1 
  └── semver@5.5.0 


$ kongfig apply --help
/usr/local/lib/node_modules/kongfig/lib/cli-apply.js:62
[...config.headers, ..._commander2.default.header].map(h => h.split(':')).forEach(([name, value]) => headers.set(name, value));
                                                                                   ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/kongfig/bin/kongfig-apply:4:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
~~~~

**Comment by CyExy** [comment]
what node version are you running on?

**Comment by CyExy** [comment]
`kongfig@1.5.2` should fix your issue.

FYI 4.x End-of-life is very near: [node release schedule](https://github.com/nodejs/Release#release-schedule)
