### ISSUE TITLE
Kongfig apply command Fails 

### ISSUE THREAD

**Issue by Rzozi** [mybuilder/kongfig#127]
When Trying to apply a config to Kong with the following command:

kongfig apply --path /config.yml --host localhost:8001

I am Getting the error: 

/usr/local/lib/node_modules/kongfig/lib/requester.js:70
  get,
     ^

SyntaxError: Unexpected token ,
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/kongfig/lib/adminApi.js:11:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

It is the first time i get this error ( using kongfig for more than a month ).

Can someone help

**Comment by CyExy** [comment]
It would be useful to know `kongfig --version` and `node --version`

Looks like a old node

**Comment by Rzozi** [comment]
Yes it did the trick, Thanks and sorry for not putting all the infos in my first post.
