### ISSUE TITLE
Apply config error -- 500 internal server error

### ISSUE THREAD

**Issue by nugrahawahyu** [mybuilder/kongfig#131]
kong version: 0.12.3

log:
```
config_1          | Loading config ./config.yml
config_1          | Apply config to kong:8001
config_1          | Error: http://kong:8001: 500 Internal Server Error 
config_1          |  Error: http://kong:8001: 500 Internal Server Error
config_1          |     at /nodejs/lib/node_modules/kongfig/lib/adminApi.js:139:25
config_1          |     at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by nugrahawahyu** [comment]
it turns out that the problem is in my network
