### ISSUE TITLE
kongfig fails when triyng to apply changes from a file

### ISSUE THREAD

**Issue by dgonzalezc** [mybuilder/kongfig#163]
**Version of kong: 0.13**

step to reproduce:
**1.- kong admin running on docker toolbox, IP 192.168.99.100:8001
2.- file dump in the local directory
3.- Executing kongfig apply --path file.yml --host 192.168.99.100:8001**

**Error**:
POST http://192.168.99.100:8001/consumers
 { username: 'si_re_td' }
201 Created { created_at: 1583255363000,
  username: 'si_re_td',
  id: '7b5b6f71-0166-42b8-ba6a-ed714ec8d777' }
(node:9272) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: http://192.168.99.100:8001/consumers/31b12b2c-160f-419c-a561-0b1cf2e20b28/hmac-auth: 500 Internal Server Error
(node:9272) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:9272) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: http://192.168.99.100:8001/consumers/a6c1d1a6-2038-41ce-95dd-ee842bd49187/oauth2: 500 Internal Server Error
Error: http://192.168.99.100:8001/consumers/a6c1d1a6-2038-41ce-95dd-ee842bd49187/acls: 500 Internal Server Error
 Error: http://192.168.99.100:8001/consumers/a6c1d1a6-2038-41ce-95dd-ee842bd49187/acls: 500 Internal Server Error
    at C:\Users\dgonzalezc\AppData\Roaming\npm\node_modules\kongfig\lib\adminApi.js:139:25
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Testing ErrorCall with Curl:**
Request:
curl http://192.168.99.100:8001/consumers/a6c1d1a6-2038-41ce-95dd-ee842bd49187/acls

Response:
{"total":1,"data":[{"group":"mc_cl_groupwhite_cau-api","created_at":1582580072000,"id":"13b57875-5a08-4ad9-a20d-dad6991afbb7","consumer_id":"a6c1d1a6-2038-41ce-95dd-ee842bd49187"}]}

**Comment by janv8000** [comment]
What's the error logged in the Kong logs, eg. `/usr/local/kong/logs/error.log` ?

**Comment by dgonzalezc** [comment]
Kong logs inside the container:
total 0
-rw-r--r--    1 root     root             0 Feb 21 13:56 error.log
-rw-r--r--    1 root     root             0 Feb 21 13:56 admin_access.log
-rw-r--r--    1 root     root             0 Feb 21 13:56 access.log
/usr/local/kong/logs # tail error.log -f

Kong container logs:
$ docker logs 002092d1107a -f --since 1s > docker_logs.txt
2020/03/11 19:15:34 [error] 19#0: *15564 [lua] responses.lua:121: handler(): FATAL: sorry, too many clients already, client: 192.168.99.1, server: kong_admin, request: "G
ET /consumers/2927468c-050a-4737-869c-2818f4aadd9e/jwt HTTP/1.1", host: "192.168.99.100:8001"
2020/03/11 19:15:34 [error] 19#0: *15567 [lua] responses.lua:121: handler(): FATAL: sorry, too many clients already, client: 192.168.99.1, server: kong_admin, request: "G
ET /consumers/2927468c-050a-4737-869c-2818f4aadd9e/acls HTTP/1.1", host: "192.168.99.100:8001"
2020/03/11 19:15:34 [error] 19#0: *15568 [lua] responses.lua:121: handler(): FATAL: sorry, too many clients already, client: 192.168.99.1, server: kong_admin, request: "G
ET /consumers/86225c68-529c-41c1-a907-5cb9272b7d74/oauth2 HTTP/1.1", host: "192.168.99.100:8001"
2020/03/11 19:15:34 [error] 19#0: *15569 [lua] responses.lua:121: handler(): FATAL: sorry, too many clients already, client: 192.168.99.1, server: kong_admin, request: "G
ET /consumers/86225c68-529c-41c1-a907-5cb9272b7d74/key-auth HTTP/1.1", host: "192.168.99.100:8001"
2020/03/11 19:15:34 [error] 19#0: *15571 [lua] responses.lua:121: handler(): FATAL: sorry, too many clients already, client: 192.168.99.1, server: kong_admin, request: "G
ET /consumers/86225c68-529c-41c1-a907-5cb9272b7d74/basic-auth HTTP/1.1", host: "192.168.99.100:8001"
2020/03/11 19:15:34 [error] 19#0: *15572 [lua] responses.lua:121: handler(): FATAL: sorry, too many clients already, client: 192.168.99.1, server: kong_admin, request: "G
ET /consumers/86225c68-529c-41c1-a907-5cb9272b7d74/hmac-auth HTTP/1.1", host: "192.168.99.100:8001"
2020/03/11 19:15:34 [error] 19#0: *15573 [lua] responses.lua:121: handler(): FATAL: sorry, too many clients already, client: 192.168.99.1, server: kong_admin, request: "G
ET /consumers/86225c68-529c-41c1-a907-5cb9272b7d74/acls HTTP/1.1", host: "192.168.99.100:8001"
2020/03/11 19:15:34 [error] 19#0: *15574 [lua] responses.lua:121: handler(): FATAL: sorry, too many clients already, client: 192.168.99.1, server: kong_admin, request: "G
ET /consumers/8d5e0ab2-4665-4618-ab10-31e9ccc5f64c/oauth2 HTTP/1.1", host: "192.168.99.100:8001"
2020/03/11 19:15:34 [error] 19#0: *15575 [lua] responses.lua:121: handler(): FATAL: sorry, too many clients already, client: 192.168.99.1, server: kong_admin, request: "G
ET /consumers/8d5e0ab2-4665-4618-ab10-31e9ccc5f64c/key-auth HTTP/1.1", host: "192.168.99.100:8001"
2020/03/11 19:15:35 [error] 19#0: *15576 [lua] responses.lua:121: handler(): FATAL: sorry, too many clients already, client: 192.168.99.1, server: kong_admin, request: "G
ET /consumers/8d5e0ab2-4665-4618-ab10-31e9ccc5f64c/jwt HTTP/1.1", host: "192.168.99.100:8001"

**Comment by dgonzalezc** [comment]
it could be a postgres max_connections config issue?

kong=# show max_connections;
 max_connections
-----------------
 100
(1 row)

kongfig apply command is sending several request to the datastore over the api of kong(in my case postgresql 9.6)

That could explain the "FATAL: sorry, too many clients already" message

**Comment by janv8000** [comment]
I had the exact same problem yesterday. 

We’re still using a pre 1.0 version of Kong and I believe they fixed a connection keep-alive issue after 1.0, possibly related: https://github.com/Kong/kong/pull/3423.  

My resolution was to set the limit to 1000. 
That’s an unreasonable high number according to PG best practices but we only use PG for Kong and are in progress of upgrading to 1.0+… After which I hope to reduce that number again or switch to using Kong without a data store …

**Comment by dgonzalezc** [comment]
i tested kong migrations up for update the datastore and run a new worker with kong 0.14.1 but does not work either, kong guys mention that a improvement was made to kong for scripting request over the admin api

https://github.com/Kong/kong/issues/3440

but it doesn't work

**Comment by dgonzalezc** [comment]
Changing the max_connections to 1000 throw me the following errors:

$ docker logs 2d0b2b7ce625 -f --since 10s | grep err
2020/03/12 17:43:20 [error] 47#0: *214325 recv() failed (104: Connection reset by peer), client: 192.168.99.1, server: kong_admin, request: "GET /consumers/e18178ec-f30d-
46ee-a23b-ffb2b7b6c278/key-auth HTTP/1.1", host: "192.168.99.100:8001"
2020/03/12 17:43:20 [error] 47#0: *214325 [lua] responses.lua:121: handler(): receive_message: failed to get type: connection reset by peer, client: 192.168.99.1, server:
 kong_admin, request: "GET /consumers/e18178ec-f30d-46ee-a23b-ffb2b7b6c278/key-auth HTTP/1.1", host: "192.168.99.100:8001"
2020/03/12 17:43:20 [error] 47#0: *214324 recv() failed (104: Connection reset by peer), client: 192.168.99.1, server: kong_admin, request: "GET /consumers/e18178ec-f30d-
46ee-a23b-ffb2b7b6c278/oauth2 HTTP/1.1", host: "192.168.99.100:8001"
2020/03/12 17:43:20 [error] 47#0: *214324 [lua] responses.lua:121: handler(): receive_message: failed to get type: connection reset by peer, client: 192.168.99.1, server:
 kong_admin, request: "GET /consumers/e18178ec-f30d-46ee-a23b-ffb2b7b6c278/oauth2 HTTP/1.1", host: "192.168.99.100:8001"
2020/03/12 17:43:20 [error] 47#0: *214323 recv() failed (104: Connection reset by peer), client: 192.168.99.1, server: kong_admin, request: "GET /consumers/87894c42-802c-
4c45-bc74-a791cde51975/acls HTTP/1.1", host: "192.168.99.100:8001"
2020/03/12 17:43:20 [error] 47#0: *214323 [lua] responses.lua:121: handler(): receive_message: failed to get type: connection reset by peer, client: 192.168.99.1, server:
 kong_admin, request: "GET /consumers/87894c42-802c-4c45-bc74-a791cde51975/acls HTTP/1.1", host: "192.168.99.100:8001"
2020/03/12 17:43:20 [error] 47#0: *214319 recv() failed (104: Connection reset by peer), client: 192.168.99.1, server: kong_admin, request: "GET /consumers/87894c42-802c-
4c45-bc74-a791cde51975/key-auth HTTP/1.1", host: "192.168.99.100:8001"
2020/03/12 17:43:20 [error] 47#0: *214319 [lua] responses.lua:121: handler(): receive_message: failed to get type: connection reset by peer, client: 192.168.99.1, server:
 kong_admin, request: "GET /consumers/87894c42-802c-4c45-bc74-a791cde51975/key-auth HTTP/1.1", host: "192.168.99.100:8001"
2020/03/12 17:43:20 [error] 47#0: *214318 recv() failed (104: Connection reset by peer), client: 192.168.99.1, server: kong_admin, request: "GET /consumers/87894c42-802c-
4c45-bc74-a791cde51975/oauth2 HTTP/1.1", host: "192.168.99.100:8001"
2020/03/12 17:43:20 [error] 47#0: *214318 [lua] responses.lua:121: handler(): receive_message: failed to get type: connection reset by peer, client: 192.168.99.1, server:
 kong_admin, request: "GET /consumers/87894c42-802c-4c45-bc74-a791cde51975/oauth2 HTTP/1.1", host: "192.168.99.100:8001"
2020/03/12 17:43:20 [error] 47#0: *214317 recv() failed (104: Connection reset by peer), client: 192.168.99.1, server: kong_admin, request: "GET /consumers/0f5a9b8a-86cd-
4aab-8f38-48c59812c857/acls HTTP/1.1", host: "192.168.99.100:8001"

**Comment by janv8000** [comment]
What's the difference between those two error logs?

**Comment by dgonzalezc** [comment]
setup:
- docker toolbox
- kongfig 1.5.3
- dump file generated

step first error:
- postgres 9.6 with max_connections=100(default)
- kong 0.13.1

steps second error:
- postgres 9.6 with max_connections=1000
- kong 0.14.1

next steps:
- test kongfig dump/apply with kong 0.15.0
- default postgres 9.6 max_connections config
