### ISSUE TITLE
can't dump kong config

### ISSUE THREAD

**Issue by forhot2000** [mybuilder/kongfig#32]
Hi,

when I dump kong config, I received an error: 

```
TypeError: acls.map is not a function
 TypeError: acls.map is not a function
    at /usr/local/lib/node_modules/kongfig/lib/readKongApi.js:70:24
    at Array.map (native)
    at parseConsumers (/usr/local/lib/node_modules/kongfig/lib/readKongApi.js:60:22)
    at /usr/local/lib/node_modules/kongfig/lib/readKongApi.js:42:44
    at run (/usr/local/lib/node_modules/kongfig/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
    at /usr/local/lib/node_modules/kongfig/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/usr/local/lib/node_modules/kongfig/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

my command is `kongfig dump --host kong:8001 --format screen`

node -version: 4.2
kong version: 0.5.1

**Comment by CyExy** [comment]
Tested it on `0.5.1` with node `v4.1.0` and `v4.4.4` dumps the sample file config with added acls just fine.

I'm going to try and add more invariant checks in, and a debug option that should help clearing this up.

**Comment by gudubeth** [comment]
I have the same problem. Dump fails inside parseConsumers function because acls is not an array. The content of "state" is something like this before the function is called:

```json
{
  "apis": [
    {
      "upstream_url": "http://httpbin.org",
      "id": "1a46a08a-b6a8-4723-b5ec-b4806f6a3442",
      "created_at": 1460555578000,
      "preserve_host": true,
      "name": "example",
      "request_host": "example.com",
      "plugins": [
        {
          "api_id": "1a46a08a-b6a8-4723-b5ec-b4806f6a3442",
          "id": "1644c4a3-bf2c-4d66-ba12-21f4575d6dc7",
          "created_at": 1460555584000,
          "enabled": true,
          "name": "custom-jwt",
          "config": {
            "claims_to_verify": [
              "exp"
            ]
          }
        }
      ]
    }
  ],
  "consumers": [
    {
      "custom_id": "example",
      "username": "example",
      "created_at": 1458731918000,
      "id": "2644c4a3-bf2c-4d66-ba12-21f4575d6dc7",
      "credentials": {
        "oauth2": [],
        "key-auth": [],
        "jwt": {
          "message": "Not found"
        },
        "basic-auth": [],
        "hmac-auth": []
      },
      "acls": {
        "message": "Not found"
      }
    }
  ]
}
```

If I bypass acl mapping, it fails on parseCredentials function.

node version: 0.12.7
kong version: 0.7.0

**Comment by CyExy** [comment]
Looks like some of the results are 404's. I think I have an idea why this is happening. Could you send me the result of `http://kong-admin/plugins/enabled`

**Comment by gudubeth** [comment]
"transformations", "custom-jwt", "custom-router" are internal plugins developed in my company. Only "custom-jwt" uses consumers. 

```json
{
  "enabled_plugins": [
    "transformations",
    "custom-jwt",
    "custom-router",
    "cors",
    "oauth2",
    "tcp-log",
    "udp-log",
    "file-log",
    "http-log",
    "key-auth",
    "hmac-auth",
    "basic-auth",
    "ip-restriction",
    "mashape-analytics",
    "request-transformer",
    "response-transformer",
    "request-size-limiting",
    "rate-limiting",
    "response-ratelimiting",
    "syslog",
    "loggly",
    "datadog"
  ]
}
```

**Comment by forhot2000** [comment]
the plugins request has been rejected by kong server because there are too many connections

```
2016/08/08 09:22:03 [error] 123#0: *1603145 [lua] responses.lua:99: handler(): FATAL: sorry, too many clients already, client: 172.17.0.7, server: , request: "GET /apis/testapi/plugins HTTP/1.1", host: "kong:8001"
```

**Comment by CyExy** [comment]
Interesting, it should keep the connection live. And reuse it. I'll investigate.

**Comment by jaygorrell** [comment]
I'm getting the same thing on this, except with enabled plugins:

```
~> kongfig dump
TypeError: json.enabled_plugins.map is not a function
 TypeError: json.enabled_plugins.map is not a function
    at /usr/local/lib/node_modules/kongfig/lib/adminApi.js:65:57
    at run (/usr/local/lib/node_modules/kongfig/node_modules/core-js/modules/es6.promise.js:87:22)
    at /usr/local/lib/node_modules/kongfig/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/usr/local/lib/node_modules/kongfig/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I do have a single enabled plugin (jwt).

**Comment by mandrewes** [comment]
I'm getting the same thing as above - I havent used babel before but it seems the polyfil is not working on my system.

**Comment by williamhorstkamp** [comment]
Getting
`TypeError: plugins.map is not a function
 TypeError: plugins.map is not a function
    at parseApiPlugins (/Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/lib/readKongApi.js:147:20)
    at parseApiPluginsForSchemes (/Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/lib/readKongApi.js:37:40)
    at /Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/lib/readKongApi.js:130:22
    at Array.map (native)
    at parseApis (/Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/lib/readKongApi.js:117:17)
    at /Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/lib/readKongApi.js:44:39
    at run (/Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/node_modules/core-js/modules/es6.promise.js:87:22)
    at /Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)`
When trying to dump the config.
Kong is running 0.9.3
Any clue what is causing this?

**Comment by CyExy** [comment]
Strange I'll have a look.

**Comment by CyExy** [comment]
@williamhorstkamp if you make a request to `curl http://localhost:8001/plugins` do you get something along the lines of `{"data":[{...}, {...}], "total" : 99}`?

**Comment by CyExy** [comment]
Released `kongfig@1.2.13` that may help you, but it will skip dumping global plugins

**Comment by jaygorrell** [comment]
@CyExy I can answer that.

```
jay@Jays-MacBook-Pro ~> kongfig dump
TypeError: json.enabled_plugins.map is not a function
 TypeError: json.enabled_plugins.map is not a function
    at /usr/local/lib/node_modules/kongfig/lib/adminApi.js:65:57
    at run (/usr/local/lib/node_modules/kongfig/node_modules/core-js/modules/es6.promise.js:87:22)
    at /usr/local/lib/node_modules/kongfig/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/usr/local/lib/node_modules/kongfig/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

```
jay@Jays-MacBook-Pro ~> curl localhost:8001/plugins
{"data":[{*snip*}],"total":5}
```

**Comment by jaygorrell** [comment]
@CyExy 

```
jay@Jays-MacBook-Pro ~> kongfig --version
1.2.13

jay@Jays-MacBook-Pro ~> kongfig dump
TypeError: json.enabled_plugins.map is not a function
 TypeError: json.enabled_plugins.map is not a function
    at /usr/local/lib/node_modules/kongfig/lib/adminApi.js:68:57
    at run (/usr/local/lib/node_modules/kongfig/node_modules/core-js/modules/es6.promise.js:87:22)
    at /usr/local/lib/node_modules/kongfig/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/usr/local/lib/node_modules/kongfig/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by CyExy** [comment]
`json.enabled_plugins.map` is different again, what version of kong are you running?

**Comment by jaygorrell** [comment]
"version": "0.9.0"

**Comment by williamhorstkamp** [comment]
@CyExy Yes, get requests to `/plugins/` return the response.
In this case I have 210 plugins.
There is seemingly nothing out of the ordinary with any calls to Kong's Admin API.

**Comment by CyExy** [comment]
They reverted the change on `Kong@0.9.3` that fixes `json.enabled_plugins.map` error, but @jaygorrell try `kongfig@1.2.14` that should do the trick.

@williamhorstkamp does the envelope contains an list `{"data": []}` or a map `{"data": {}}`. If it is an array then there might be an issue with pagination.

**Comment by williamhorstkamp** [comment]
Ahh, I see what you mean. It is returning `{"data": []}`

**Comment by jaygorrell** [comment]
New error with 1.2.14, appears to be with my consumer using a custom id:

```
Jay@Jays-MacBook-Pro ~> kongfig dump
Consumers with only custom_id not supported: auth-service
TypeError: Cannot convert undefined or null to object
 TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at /usr/local/lib/node_modules/kongfig/lib/readKongApi.js:81:37
    at Array.map (native)
    at parseConsumers (/usr/local/lib/node_modules/kongfig/lib/readKongApi.js:64:22)
    at /usr/local/lib/node_modules/kongfig/lib/readKongApi.js:45:44
    at run (/usr/local/lib/node_modules/kongfig/node_modules/core-js/modules/es6.promise.js:87:22)
    at /usr/local/lib/node_modules/kongfig/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/usr/local/lib/node_modules/kongfig/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by williamhorstkamp** [comment]
With 1.2.14 I get
```
FetchError: request to {{URL REDACTED}}/plugins/schema/galileo failed, reason: connect ETIMEDOUT {{IP REDACTED}}
 FetchError: request to {{URL REDACTED}}/plugins/schema/galileo failed, reason: connect ETIMEDOUT {{IP REDACTED}}
    at ClientRequest.<anonymous> (/Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by CyExy** [comment]
Ok added a bit more error handling for responses `kongfig@1.2.15` it may be that some of the responses are non 2xx.

**Comment by CyExy** [comment]
It would probably make more sense to back off a little and then retry.

**Comment by jaygorrell** [comment]
No change in messaging for 1.2.15 for me

**Comment by williamhorstkamp** [comment]
Now getting
```
Error: Not Found
 Error: Not Found
    at handleError (/Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/lib/adminApi.js:123:21)
    at run (/Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/node_modules/core-js/modules/es6.promise.js:87:22)
    at /Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by CyExy** [comment]
@jaygorrell I think you are hitting #29 probably best to ignore consumers till this get added, run with `--ignore-consumers` option.

@williamhorstkamp `kongfig@1.2.16` adds retry and gives a little more info when it fails

**Comment by jaygorrell** [comment]
Perfect, thanks @CyExy. I'm good on this specific issue, then, once others (@williamhorstkamp) are clear. Thanks for the help!

**Comment by williamhorstkamp** [comment]
Here it is on 1.2.16
```
Error: {{url redacted}}/apis/undefined/plugins: Not Found
 Error: {{url redacted}}/apis/undefined/plugins: Not Found
    at /Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/lib/adminApi.js:113:25
    at run (/Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/node_modules/core-js/modules/es6.promise.js:87:22)
    at /Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by CyExy** [comment]
@williamhorstkamp try `kongfig@1.2.17`

@jaygorrell Thank you for helping out!

**Comment by williamhorstkamp** [comment]
Same error @CyExy

**Comment by CyExy** [comment]
Somehow one of the APIs that are coming down doesn't have a name nor an id. I'll try to fix it tomorrow (GMT). Thanks for reporting it!

**Comment by williamhorstkamp** [comment]
Just let me know if I can help in any way, and thank you for jumping on this so quickly!

**Comment by CyExy** [comment]
@williamhorstkamp kongfig@1.2.18 should now fail just before it tries to fetch the plugins, hopefully outputting the whole API definition.

**Comment by williamhorstkamp** [comment]
@CyExy this is what I get with 1.2.18:
```
Error: "API doesn't have an Id: {
  "_c": [],
  "_s": 0,
  "_d": false,
  "_h": 0,
  "_n": false
} 
 Error: "API doesn't have an Id: {
  "_c": [],
  "_s": 0,
  "_d": false,
  "_h": 0,
  "_n": false
}
    at Error (native)
    at _callee$ (/Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/lib/kongState.js:48:55)
    at tryCatch (/Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/node_modules/regenerator-runtime/runtime.js:95:21)
    at step (/Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/lib/kongState.js:15:273)
    at /Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/lib/kongState.js:15:443
    at new Promise (/Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/node_modules/core-js/modules/es6.promise.js:191:7)
    at /Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/lib/kongState.js:15:99
    at /Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/lib/kongState.js:67:44

```

**Comment by CyExy** [comment]
Looks like a Promise but how did it get there!?

**Comment by CyExy** [comment]
Are you able to build from master? It would probably be easier then to publishing new versions for debugging.

```
npm install --global babel-cli

git clone git@github.com:mybuilder/kongfig.git
cd kongfig

npm install
npm run build -- --watch

then you should have `bin/kongfig`
```

**Comment by williamhorstkamp** [comment]
Yea, I was able to build it.

**Comment by CyExy** [comment]
Ok, hope `kongfig@1.2.19` fixes it.

**Comment by CyExy** [comment]
FIY should be able to install it as usual.

**Comment by williamhorstkamp** [comment]
Seemingly just hanging when I try to dump the offending kong configuration.
Still works fine on other, less complex, configurations.

**Comment by williamhorstkamp** [comment]
I just have it running in a terminal window, hopefully it finishes at some point.

**Comment by CyExy** [comment]
If you have a lot of data then it may take a while. How many consumers and apis do you have?

**Comment by williamhorstkamp** [comment]
I am using the --ignore-consumers flag, 108 APIs each with 1-3 plugins.

**Comment by CyExy** [comment]
Sounds like its in a loop.

**Comment by williamhorstkamp** [comment]
```
FetchError: request to {{url redacted}}/apis?size=100&offset=ABAB0T4gkfRGiLPCAeyPm7ToAA8ADHVwc3RyZWFtX3VybAB%2F%2F%2F%2Bb failed, reason: connect ECONNREFUSED {{ip redacted}}
 FetchError: request to {{url redacted}}/apis?size=100&offset=ABAB0T4gkfRGiLPCAeyPm7ToAA8ADHVwc3RyZWFtX3VybAB%2F%2F%2F%2Bb failed, reason: connect ECONNREFUSED {{ip redacted}}
    at ClientRequest.<anonymous> (/Users/wjhorstkamp/.nvm/versions/node/v6.3.0/lib/node_modules/kongfig/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by williamhorstkamp** [comment]
Same error when trying to apply as well.

**Comment by CyExy** [comment]
You are hitting some kind of rate limiting. Are you connecting directly to Kong or through a proxy?

**Comment by williamhorstkamp** [comment]
We are using Kong as a proxy to itself. The only two plugins are key-auth and acl, which we are using to limit access to the admin consumer.

**Comment by CyExy** [comment]
`kongfig@1.2.21` adds exponential backoff to retry that may help.

**Comment by williamhorstkamp** [comment]
Same thing. Did a little experimenting.
When I hit `{{kong admin public dns}}/apis?size=100` I get a value for next like '{{kong internal elasticbeanstalk dns}}/apis?size=100&offset={{offset id}}.` If I try this link, the request hangs and eventually times out, but if I change the link to `{{kong admin public dns}}/apis?size=100&offset={{same offset id as before}}` I can successfully hit the next page.

**Comment by CyExy** [comment]
Interesting it basically picks up the internal host, try doing the request again and set X-FORWARDED-HOST header to your public admin host. If that works you can specify custom headers in kongfig as well with `--header` option

**Comment by williamhorstkamp** [comment]
Still doesn't work.

**Comment by CyExy** [comment]
Make sure that your kong admin api definition has `preserve_host: true`

**Comment by CyExy** [comment]
Another thing to look out for is if you have set e.g. `request_path: /kong-admin` and `strip_request_path: true` then the next URL will be incorrect, regardless of what you do.

Another option would be for kongfig to re-map query parameters onto the original URL, that would fix it. Strictly speaking, it's not playing nice with discoverable URLs, but I very much doubt it will be a problem.

**Comment by williamhorstkamp** [comment]
Awesome, using `preserve_host` completely fixed the problem, setting `X-FORWARDED-HOST` was not necissary.

**Comment by CyExy** [comment]
Great stuff, thanks for reporting it and helping me to fix some bugs :)

**Comment by williamhorstkamp** [comment]
And thank you for jumping on the issue so quickly!
