### ISSUE TITLE
Problem when using a host with an invalid SSL certificate

### ISSUE THREAD

**Issue by jmdacruz** [mybuilder/kongfig#44]
In certain cases, we use self-signed certificates on development environments and such. In these situations, it's important to be able to ignore certificate issues such as the one below (caused by calling `kongfig dump --https --host ${HOSTNAME}`)

Is there a way to change this behavior?

```
FetchError: request to https://bastion.intpsi043.ipsi.tm-data.infra-host.com:8001/api/v1/proxy/namespaces/intpsi043/services/kong//apis failed, reason: self signed certificate
 FetchError: request to https://bastion.intpsi043.ipsi.tm-data.infra-host.com:8001/api/v1/proxy/namespaces/intpsi043/services/kong//apis failed, reason: self signed certificate
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/kongfig/node_modules/node-fetch/index.js:127:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by jmdacruz** [comment]
I think I found the answer myself... since the call is finally routed to the `https` core module, then doing `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"` disables the warning. I can set this as an environment variable before calling `kongfig` (which would be something like `export NODE_TLS_REJECT_UNAUTHORIZED=0`) et voilà!

**Comment by CyExy** [comment]
Good find, that would be a great addition to [README.md](https://github.com/mybuilder/kongfig/blob/master/README.md)
