### ISSUE TITLE
Load plugins that don't have config?

### ISSUE THREAD

**Issue by smitchelus** [mybuilder/kongfig#66]
Hi, I'm trying to load a global plugin that looks like:
```  
- name: sl-api-name-plugin
    attributes:
      enabled: true
```
The plugin does not have any configurable attributes and when I attempt to load this is generates an error:
```
TypeError: Cannot convert undefined or null to object
 TypeError: Cannot convert undefined or null to object
    at exports.default (/opt/nodes/6.3.0/lib/node_modules/kongfig/lib/diff.js:24:23)
    at Object.isGlobalPluginUpToDate (/opt/nodes/6.3.0/lib/node_modules/kongfig/lib/core.js:414:39)
    at /opt/nodes/6.3.0/lib/node_modules/kongfig/lib/core.js:532:23
    at _callee3$ (/opt/nodes/6.3.0/lib/node_modules/kongfig/lib/core.js:193:63)
    at tryCatch (/opt/nodes/6.3.0/lib/node_modules/kongfig/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/opt/nodes/6.3.0/lib/node_modules/kongf
```

If I add a bogus attribute it makes it further through the process and then, appropriately, errors out complaining about an unknown configuration field:
```
PATCH 400 http://localhost:8001/plugins/fc379df7-7a4d-4fd7-9727-d829a014b9bb
 { enabled: true, config: { bogus: 'value' } }
Error: Bad Request
{"config.bogus":"bogus is an unknown field"}

 Error: Bad Request
{"config.bogus":"bogus is an unknown field"}

    at /opt/nodes/6.3.0/lib/node_modules/kongfig/lib/core.js:158:43
    at run (/opt/nodes/6.3.0/lib/node_modules/kongfig/node_modules/core-js/modules/es6.promise.js:87:22)
```
Can you confirm what I'm seeing, and do you see any reason this shouldn't be supported?

FYI, I am running version `1.3.0`

**Comment by CyExy** [comment]
Did you try adding an empty config, `config: {}`?

**Comment by smitchelus** [comment]
Yes, I've tried the following and can confirm it generates the same error:
```
  - name: sl-api-name-plugin
    attributes:
      enabled: true
      config:

```

**Comment by CyExy** [comment]
I'll do a fix but try to set it to `{}`

```
  - name: sl-api-name-plugin
    attributes:
      enabled: true
      config: {}
```

**Comment by smitchelus** [comment]
Thanks, that did work. Honestly, I didn't realize that was legal YAML. Thanks for the clarification (I was thinking you were showing me a JSON representation the first time). I'm good to go at this point.
