### ISSUE TITLE
kongfig apply errors out

### ISSUE THREAD

**Issue by mrafieee** [mybuilder/kongfig#85]
my kong version is 0.10.3 and my dump is from 1.0.2 version
```
$ kongfig apply --path new.yaml --host x.x.x.x:8001
Loading config new.yaml
Apply config to x.x.x.x
Error: http://x.x.x.x:8001/apis/b96b87a1-5023-43c3-a311-dbef3026cd8c/plugins: 500 Internal Server Error 
 Error: http://x.x.x.x:8001/apis/b96b87a1-5023-43c3-a311-dbef3026cd8c/plugins: 500 Internal Server Error
    at /usr/lib/node_modules/kongfig/lib/adminApi.js:125:25
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```
how can I get more details on error?

**Comment by CyExy** [comment]
Can you submit a config that would reproduce it?

**Comment by CyExy** [comment]
Closing this as no response, please reopen if it keeps happening.
